### ISSUE TITLE
Epirus Can't Occupy a City

### ISSUE THREAD

**Issue by watuti** [ravignir/Ancient-Civilizations#13]
I`m not sure whether  this is a bug or that's how it is meant or that's  just how it works but..
The Epirus tribe cant conquer a city 
!
![i won but](https://user-images.githubusercontent.com/89923749/131688541-b116b2ea-be93-467b-91dd-e5f45c0cf7e1.jpg)

It says that we have conquered the city but the city just turns into ruins instead. And also capturing a settler turns them into worker??
Also its quite hard to defeat a city on other starting eras. I had to start on Medieval era on settler difficulty just to defeat a city.
maybe the civ have more starting unit,  or maybe the general (settler) boosts the stats of units  around him 
 
Other than that this mod is really cool and I really like the idea of the Epirus civ. Hope this helped :))) <3

**Comment by maxime1147** [comment]
Also, civilians can't occupy city tiles acquired by outposts which are outside the normal city range.
